language: python
python: 3.5

before_script:
  - psql -c "create user ormdbuser with password 'ormDbPass';" -U postgres
  - psql -c "create database asyncorm;" -U postgres
  - psql -c "grant all privileges on database asyncorm to ormdbuser;" -U postgres
  - psql -c "alter user ormdbuser with superuser;" -U postgres

services:
  - postgresql

# command to install dependencies
install: "pip install -r requirements.txt"

env:
  - sanic=0.5.4
  - sanic=0.5.5

# command to run tests
script: python -m tests
