language: python
python:
  - "3.5"
  - "3.6"

before_script:
  - psql -c "create user ormdbuser with password 'ormDbPass';" -U postgres
  - psql -c "create database asyncorm;" -U postgres
  - psql -c "grant all privileges on database asyncorm to ormdbuser;" -U postgres
  - psql -c "alter user ormdbuser with superuser;" -U postgres

services:
  - postgresql

#env:
#  - SANIC_VERSION=0.5.4
#  - SANIC_VERSION=0.5.5

# command to install dependencies
install:
  # - pip install -q sanic==$SANIC_VERSION
  - pip install -r requirements.txt

# command to run tests
script: python -m tests
